name: Terraform Plan on PR

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform apply

      - name: Post Plan Results on PR
        uses: actions/github-script@v6
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   script: |
        #     const fs = require('fs');
        #     const planOutput = fs.readFileSync('tfplan', 'utf8');
        #     const summary = `
        #     ### Terraform Plan Summary
        #     \`\`\`
        #     ${planOutput}
        #     \`\`\`
        #     `;
